% Decode('压缩图像.jpg','qq.jpg');
img_shape = [512,540];
file_name = 'all.dat';
fid = fopen(file_name,'rb');
image = fread(fid,img_shape,'uint16');
image(:,end) = image(:,end-1);
MAX = max(max(image));
MIN = min(min(image));
image = uint8(255*(image-MIN)/(MAX-MIN));
% re = image(1:16,1:16);
imwrite(image,'re.bmp');
imshow(image);